You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\topologies\server.js:564:11)
    at Pool.emit (events.js:182:13)
    at Connection.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\pool.js:317:12)
    at Object.onceWrapper (events.js:273:13)
    at Connection.emit (events.js:182:13)
    at Socket.<anonymous> (E:\project\node\my-blog\node_modules\mongodb-core\lib\connection\connection.js:246:50)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at args.(anonymous function) (D:\devsoft\nodejs\node_global\node_modules\pm2\node_modules\event-loop-inspector\index.js:138:29)
    at process._tickCallback (internal/process/next_tick.js:63:19)
